# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c7c93ab6848f2b8b66966aa3b633b38f5d9ad32dabf87db8c373859be0f608db67987ca796281ef50e600955f6ab410c1062ab919f53571a2f9fec1aa6cf695

test:
  secret_key_base: 10fca117b5de0de6007d12adab2a7ce8baf5fd74d08bec347098e90db3d23bac0a7f1a2485353cff01e19efb9ed74a99007feb0e40b3a717277db68807a848ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
